### ISSUE TITLE
Game Design

### ISSUE THREAD

**Issue by vorble** [vorble/greatestparty#3]
I've been working with @lledargo to design elements of the game, implement the levels, and brainstorm how the game should work. This issue is for getting to the bottom of some game design elements to help us get to a point where the fundamental structure is in place.

## Yes Things
* ~~Add basic stat modifiers to the party.~~ https://github.com/vorble/greatestparty/commit/dbe1c43723ba1e0e3de30b6b84744ce8225fb950
* ~~Add usable items to boost things like basic stats, learn skills.~~ https://github.com/vorble/greatestparty/commit/63a40c49de925f34ad1c097a5238f57617eb1b3a https://github.com/vorble/greatestparty/commit/b01e67155aadb7e7805cd9642cb50ac78e5b139b
* ~~Move party stats and statuses into party panel.~~ https://github.com/vorble/greatestparty/commit/d6caab2430255e62332b69b8cd85e0dc6d7c5995 https://github.com/vorble/greatestparty/commit/40a95256d954829a16b2e0b34d791879ecd8241d
* ~~Expand status system to work with:~~ https://github.com/vorble/greatestparty/commit/63a40c49de925f34ad1c097a5238f57617eb1b3a
  * ~~Usable items.~~
  * ~~Action buttons.~~
  * ~~Events.~~
* ~~Item ideas:~~
  * ~~Tome of Knowledge, +int permanently.~~ https://github.com/vorble/greatestparty/commit/f595cbcfef0be502d55074b2e74047f5bf20ccf3
  * ~~Cleric Robes: prevent 69 de-alignment points or something.~~ https://github.com/vorble/greatestparty/commit/f595cbcfef0be502d55074b2e74047f5bf20ccf3
  * ~~Weapon Boost: +1 equippable weapon slots.~~ https://github.com/vorble/greatestparty/commit/1634a069dcf3376ed4253c974cecadcef58fd73d
  * ~~Armor Boost: +1 equippable armor slots.~~ https://github.com/vorble/greatestparty/commit/1634a069dcf3376ed4253c974cecadcef58fd73d
* ~~Level progression.~~ Level progressions have been possible since near the start of the project, we just need a sufficient number of levels.
* ~~Game specific events (agnostic of which level/town you're in).~~ https://github.com/vorble/greatestparty/commit/b18a211bb08063067b4b7e4934874283f69900b0
* ~~Non-boss enemies.~~ https://github.com/vorble/greatestparty/commit/dd92a51e3fb6ef4fa704899dc95f5d0990a2c58d
* ~~Rework of boss fights to be like non-boss fights.~~ https://github.com/vorble/greatestparty/commit/43ce86799b342922becb8a38cddc166b2c3beae5
* ~~Quests.~~ https://github.com/vorble/greatestparty/commit/f4b927c1da26293a6c00d1690dc714fcfa6b3fd1 

## Maybe Things
* Skill ideas:
  * Drink blood for stat boost?
 
## Technical Junk
* ~~Rework the underpinnings of the `Party` and `Boss` classes in preparation for more battle opportunities.~~ https://github.com/vorble/greatestparty/commit/dd92a51e3fb6ef4fa704899dc95f5d0990a2c58d

**Comment by vorble** [comment]
Some of my game design notes as of May 4, 2021

* More battles besides the boss battle would make the game more fun. As I played the two towns, I thought it would be fun to fight smaller battles and receive loot and gold at the risk of losing party members. With the current design, the battles could be implemented as normal town events, but that takes away from the general adventure vibe that town events are supposed to put out there (now your general questing is replaced by battles some portion of the time). I think if there was a separate script of enemies in a town with whom battles occur outside of the town events cycle it would be nice.
* Quest lines with key items and bonuses would be great, giving some lore-oriented reasons to stick around a town. Quest lines could open or close based on the party's alignment with the town and/or other things the party does (e.g. they may not like you if you are sacrificing your party members).
* I haven't made as much use of the party statuses as I'd like. I was envisioning statuses being applied by certain types of loot, but right now it's just curses. I think statuses will be easier to come up with once the game mechanics and calculations are more fleshed out.

**Comment by vorble** [comment]
It's also turning out that there's a bunch of functions I have to call during each town event in order for Palm Town to work as intended. It might make sense to readdress the town events system (and boss event system) to have more flexibility. For example, it might be easier to express the town's functionality if there are event hooks you can use to do actions per tick, tock, 5 tocks (current town/boss event schedule), term, season, or year.

**Comment by lledargo** [comment]
>     * More battles besides the boss battle would make the game more fun. As I played the two towns, I thought it would be fun to fight smaller battles and receive loot and gold at the risk of losing party members. With the current design, the battles could be implemented as normal town events, but that takes away from the general adventure vibe that town events are supposed to put out there (now your general questing is replaced by battles some portion of the time). I think if there was a separate script of enemies in a town with whom battles occur outside of the town events cycle it would be nice.

I kind of go back and forth on wanting this, I feel it will diminish some of the replay value by always having the same story or campaign in a town. If we do this though I do not think it should just be battles, we could also have one-time non-fighting quests included in the progression. 

>     * Quest lines with key items and bonuses would be great, giving some lore-oriented reasons to stick around a town. Quest lines could open or close based on the party's alignment with the town and/or other things the party does (e.g. they may not like you if you are sacrificing your party members).

I've been contemplating special items too. I like the idea of being able to collect items that can help in future situations. Like a Tome of Knowledge you can read to boost int, armor that gives you more armor equipment slots, cleric robes which allow for certain levels of conscription without losing town alignment, etc. Currently we have nowhere to keep these items though

 
>     * I haven't made as much use of the party statuses as I'd like. I was envisioning statuses being applied by certain types of loot, but right now it's just curses. I think statuses will be easier to come up with once the game mechanics and calculations are more fleshed out.

I think Statuses (Stati?) would be useful to track the effects of the items I've listed above. I'd like to keep them for now because I think we can make good use of them in the near future.

**Comment by lledargo** [comment]
I do really like the idea of doing certain actions at a regular interval. Right now it feels like, the actions in an event are meant to lead to the functions being run.

I was also thinking, it seems like 1-2 events occur every few tocks currently. As you gain more party members, it seems they would work faster and more events would happen. We could tie the number of events per cycle to the party's size somehow allowing more events to happen.

**Comment by lledargo** [comment]
I'd like to see something that lets me add a modifier to the party stats. Maybe you drink a dex potion that temporarily give you +2 to dex. I could just increment or decrement the game.party.dex, but it seems like it would be more appropriate to set a game.party.dexmod which is automatically appliedwhen I call game.party.dex. 

I thought I might do this in game.ts when you roll the stats, but I know we would not want to do 'this.party.dex = topThreeOfFourD6() + this.party.dexmod;' because that will just apply a 0 mod at the beginning of the game and will not recalculate when you set dexmod. Where else could we do this?

**Comment by vorble** [comment]
> I'd like to see something that lets me add a modifier to the party stats. Maybe you drink a dex potion that temporarily give you +2 to dex. I could just increment or decrement the game.party.dex, but it seems like it would be more appropriate to set a game.party.dexmod which is automatically appliedwhen I call game.party.dex.
> 
> I thought I might do this in game.ts when you roll the stats, but I know we would not want to do 'this.party.dex = topThreeOfFourD6() + this.party.dexmod;' because that will just apply a 0 mod at the beginning of the game and will not recalculate when you set dexmod. Where else could we do this?

We could use a getter on the `Party` class to apply the mod, something along these lines:

```javascript
class Party {
  dexbase: number;
  dexmod: number;
...
  get dex(): number {
    return this.dexbase + this.dexmod;
  }
```

Not much would have to change elsewhere.

As for things that would change a modifier, I think it would be usable items (great idea), status effects, potentially new action buttons (e.g. learn a skill to let you drink the sacrificial blood for a stat boost). We can expand upon the status class's clock callbacks to add callbacks for when the status is activated and deactivated. We'd need something similar for items, so I think it'd be good to rework the status system to make it work for all three purposes.

I'm going to keep some aggregate notes in the main issue text.

**Comment by vorble** [comment]
> I do really like the idea of doing certain actions at a regular interval. Right now it feels like, the actions in an event are meant to lead to the functions being run.
> 
> I was also thinking, it seems like 1-2 events occur every few tocks currently. As you gain more party members, it seems they would work faster and more events would happen. We could tie the number of events per cycle to the party's size somehow allowing more events to happen.

What do you think about splitting the events system up some more? For example, there would be events that trigger when you are doing a quest (0 quests, 0 such actions, many quests, many such actions). There would be general environment/town events, curse events like Angered Gods, events from skills like Inspire, and probably some more. Essentially, most aspects of the game will plug into the event handling system in some way.

**Comment by lledargo** [comment]
> > I do really like the idea of doing certain actions at a regular interval. Right now it feels like, the actions in an event are meant to lead to the functions being run.
> > I was also thinking, it seems like 1-2 events occur every few tocks currently. As you gain more party members, it seems they would work faster and more events would happen. We could tie the number of events per cycle to the party's size somehow allowing more events to happen.
> 
> What do you think about splitting the events system up some more? For example, there would be events that trigger when you are doing a quest (0 quests, 0 such actions, many quests, many such actions). There would be general environment/town events, curse events like Angered Gods, events from skills like Inspire, and probably some more. Essentially, most aspects of the game will plug into the event handling system in some way.

I think that is a pretty elegant solution. Coincidentally, I actually rewrote angered gods as an event rather than a function earlier today.

**Comment by lledargo** [comment]
> As for things that would change a modifier, I think it would be usable items (great idea), status effects, potentially new action buttons (e.g. learn a skill to let you drink the sacrificial blood for a stat boost). We can expand upon the status class's clock callbacks to add callbacks for when the status is activated and deactivated. We'd need something similar for items, so I think it'd be good to rework the status system to make it work for all three purposes.

My current use case for stat modifiers is an attack I am adding to the Magma Elemental. It will stomp, creating a shock wave and temporarily decreasing the party's dexterity.

**Comment by lledargo** [comment]
Hey, lets not forget level progression in your notes.

**Comment by lledargo** [comment]
I'm working on a couple of town events (Farm Aid and Vigilantism) which could be considered town-agnostic. Somehow we could work these into an array of events that can happen in any town.

**Comment by vorble** [comment]
> > As for things that would change a modifier, I think it would be usable items (great idea), status effects, potentially new action buttons (e.g. learn a skill to let you drink the sacrificial blood for a stat boost). We can expand upon the status class's clock callbacks to add callbacks for when the status is activated and deactivated. We'd need something similar for items, so I think it'd be good to rework the status system to make it work for all three purposes.
> 
> My current use case for stat modifiers is an attack I am adding to the Magma Elemental. It will stomp, creating a shock wave and temporarily decreasing the party's dexterity.

I'm going to work on adding the modifiers for you tonight.

**Comment by vorble** [comment]
> > > As for things that would change a modifier, I think it would be usable items (great idea), status effects, potentially new action buttons (e.g. learn a skill to let you drink the sacrificial blood for a stat boost). We can expand upon the status class's clock callbacks to add callbacks for when the status is activated and deactivated. We'd need something similar for items, so I think it'd be good to rework the status system to make it work for all three purposes.
> > 
> > 
> > My current use case for stat modifiers is an attack I am adding to the Magma Elemental. It will stomp, creating a shock wave and temporarily decreasing the party's dexterity.
> 
> I'm going to work on adding the modifiers for you tonight.

Added the stat modifiers in https://github.com/vorble/greatestparty/commit/dbe1c43723ba1e0e3de30b6b84744ce8225fb950 . I cap the effective stats at 0 and above, but there's no real reason they can't go negative.

@lledargo I enabled the one dexmod adjustment you had commented out in Magma Town and added a function to the game object to allow timeouts to get set so that the dexmod can be restored after a while. I don't think I'll take that approach forever with regards to temporary stat changes, but it should let you make the town's events work how you want for now.

**Comment by lledargo** [comment]
I've merge the stat modifiers into my repo too, thanks!

In 0665581 I added a function I've called bellMod. It returns a modifier value that is nice for adding to dice rolls. I realize now is not on a bell curve, so we should probably rename it. I think it belongs in chance.ts or game.ts, but for now it will leave it in level02.ts

The Vigilantism event from that same commit is a working example of something that could be repurposed into a town-agnostic event, once that type of event is implemented. It's turning out to be a longer event which is something I want to do with more events, town-specific events included. 

I had one final thought for now, I keep getting great stats most of the time, that can be kind of boring when it happens to often though. I think we should switch to a 3d6 (instead of 4d6 + drop the lowest)or 2d8 per stat. 3d6 will just result in a slightly lower average roll, 2d8 will lower the average roll value even more and change the roll-able range from 3-18 to 2-16. Lower stats will of course make the game more challenging and exciting as defeat is waiting around every corner.

As I was writing that last paragraph I realized we could implement mild, medium, and spicy modes by rolling different combinations of die.

**Comment by vorble** [comment]
> I've merge the stat modifiers into my repo too, thanks!
> 
> In [0665581](https://github.com/vorble/greatestparty/commit/0665581713ba5cdc4180cba27d5fec38fc615aef) I added a function I've called bellMod. It returns a modifier value that is nice for adding to dice rolls. I realize now is not on a bell curve, so we should probably rename it. I think it belongs in chance.ts or game.ts, but for now it will leave it in level02.ts
> 
> The Vigilantism event from that same commit is a working example of something that could be repurposed into a town-agnostic event, once that type of event is implemented. It's turning out to be a longer event which is something I want to do with more events, town-specific events included.
> 
> I had one final thought for now, I keep getting great stats most of the time, that can be kind of boring when it happens to often though. I think we should switch to a 3d6 (instead of 4d6 + drop the lowest)or 2d8 per stat. 3d6 will just result in a slightly lower average roll, 2d8 will lower the average roll value even more and change the roll-able range from 3-18 to 2-16. Lower stats will of course make the game more challenging and exciting as defeat is waiting around every corner.
> 
> As I was writing that last paragraph I realized we could implement mild, medium, and spicy modes by rolling different combinations of die.

I agree that the party stats are generally too high, I've always have a few stats >= 13 which seems like too much.

I made some histograms of various rolling schemes:

```
4d6 top 3
03 
04 
05 
06 *
07 **
08 ****
09 *******
10 *********
11 ***********
12 *************
13 *************
14 ************
15 **********
16 *******
17 ****
18 *

4d6 top 3, inverted bell (21 - 4d6 top 3)
03 *
04 ****
05 *******
06 **********
07 ************
08 *************
09 ************
10 ***********
11 *********
12 *******
13 ****
14 **
15 *
16 
17 
18 

4d6 bottom 3
03 *
04 ****
05 *******
06 **********
07 ************
08 *************
09 ************
10 ***********
11 *********
12 ******
13 ****
14 **
15 *
16 
17 
18 

3d6
03 
04 *
05 **
06 ****
07 ******
08 *********
09 ***********
10 ************
11 ************
12 ***********
13 *********
14 ******
15 ****
16 **
17 *
18 

2d8
02 *
03 ***
04 ****
05 ******
06 *******
07 *********
08 ***********
09 ************
10 **********
11 *********
12 *******
13 ******
14 ****
15 ***
16 *
```

I like 2d8 because it gives more chances to get the extreme lows/highs.

**Comment by vorble** [comment]
@lledargo what do you think about 4d6 bottom 3?

**Comment by lledargo** [comment]
I like the idea of the average stat roll being slightly challenging. I make a lot of things a near tossup if your stat is 10, so I would say an 8 or 9 on any stat roll would be 'slightly challenging'. Its hard for me to decide between 2d8 and 4d6 bottom 3 but you make a valid point about the additional variance of 2d8, and having the occasional high stat can be great fun. 
I had a couple of other ideas that could be fun for stat rolls:
1. `1d20` - not only can you roll any value between 1 and 20. The even distribution would ensure you almost always have at least 1 of each great, average, and terrible stats.
2. `1d20 + linearMod(1d20)` - this would have a lot of problems lol, but you can see how it would be interesting 
3.  `2d10 (or 2d9)` - get benefits of the same type of distribution as 2d8, but expand the range to 2 - 18 or 20.

**Comment by vorble** [comment]
Check this out, 3d6 no 5's:

```
3d6 no 5
03 
04 **
05 ****
06 *******
07 *********
08 ************
09 ************
10 ************
11 ************
12 *******
13 *******
14 ****
15 **
16 **
18 
```

No 17's though since you can't get 17 from the sum of 3 from 1 to 6 without 5's. Might be pretty capricious tho since it took 1,000,000 samples to get the histogram to smooth out (other histos were 100,000 samples).

**Comment by vorble** [comment]
Running out of space for new stuff, so for the usable items I'm going to have to rearrange some things. Here's what I have in mind:

* Combine stats from middle-left into the party display.
* Combine statuses from bottom-left into the party display.

That'll will give two open spaces to put stuff in and I'll use one for now for the items.

**Comment by vorble** [comment]
@lledargo I whipped through a bunch of stuff with usable items and statuses. Let me know what you think. If you play the level I've been working on, sometimes it drops potions as loot. Otherwise you can fiddle around with `game.party.items.potionStrUp1.quantity` to give yourself some. There are items for each of the main stats. More items to come.

**Comment by vorble** [comment]
Looks like the list is complete. Probably time to start hunkering down and cleaning up the mess I made along the way.

@lledargo Any last features you can think of?
